#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

#define QUICK_TAP_TERM 0

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 2

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 50

#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#define MOUSEKEY_WHEEL_TIME_TO_MAX 30

#define SERIAL_NUMBER "4JlZ4/Kr0lV7"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

